# NB01: Data Collection

**LSE ME204 – Data Engineering Principles for the Social Sciences (2026)**

**LSE ID:** 250093214

## Setup

Run the cell below to ensure all required packages are installed before running all other cells.

In [1]:
import json
import requests
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

## The question

Power creep is defined as "the strengthening of [a] game and its pieces over time possibly to the point where new pieces invalidate older ones" [(Magruder, 2022)](https://journals.sagepub.com/doi/full/10.1177/15554120211050812#bibr20-15554120211050812). This occurs because developers want to keep their games fresh and exciting in order to keep players coming back [(Magic the Gathering on new cards sets)](https://magic.wizards.com/en/news/card-preview/fire-it-2019-06-21). However, too much power creep can make a game unrecognizeable. One card game that is perhaps infamous for power creep is Yu-Gi-Oh. One search on Reddit will provide many posts from both dedicated Yu-Gi-Oh subreddits and other card game subreddits discussing the power creep in Yu-Gi-Oh. Some posts are as old as five years, some as recent as two months ago, showing how pervasive and long-lasting the issue of power creep is. (Re-watch RTGame Yu-Gi-Oh video about coming back to the game). 

Yu-Gi-Oh has been around for nearly 30 years, and though power creep is an issue, it has still been going strong. Another franchise that has been going arguably stronger for the same length of time is Pokemon. It is so beloved that parents that grew up with Pokemon are now sharing it with their own children [(Amenabar, 2022)](https://www.washingtonpost.com/video-games/2022/08/10/pokemon-starter-parents-kids/). Yu-Gi-Oh has not experienced the same rite-of-passage experience as Pokemon has, in part due to how complicated the game is [(short Reddit thread about the subject)](https://www.reddit.com/r/Yugioh101/comments/onn3vm/dear_parents_do_your_kids_play_yugioh_and_is_it/). If Pokemon experiences power creep in the same way, this parental bonding method might not be as effective any more. Additionally, fans could get tired of having to buy all of the new games and DLC just to get access to all of the new, strong Pokemon. However, this would only occur if Pokemon experiences a high level of power creep.

Question: Has Pokemon experienced power creep over its thirty years of existance? If so, to what extent is power creep experienced?


## Where is the data coming from to answer this question?

All data collected to answer this question comes from [PokeAPI](https://pokeapi.co/docs/v2). This is a robust API offering endpoints for many different kinds of Pokemon data, but the three I will be collecting data on are their [Generation API](https://pokeapi.co/docs/v2#games-section), their [Pokemon Species API](https://pokeapi.co/docs/v2#pokemon-species), and their [Pokemon API](https://pokeapi.co/docs/v2#pokemon).

Suppelementary data will be retrieved from either [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Main_Page), [Pokemon Database](https://pokemondb.net/), or [Serebii.net](https://www.serebii.net/).

## Getting a list of all Pokemon

First, I am going to use PokeAPI's Generation API to collect a list of all of the Pokemon species introduced in every generation. A species, as defined by PokeAPI, "forms the basis for at least one Pokemon." For instance, take the Pokemon Wormadam. Wormadam has three forms based on its cloak: Plant Cloak, Sandy Cloak, and Trash Cloak, but Wormadam is the underlying species of all three forms.

In [2]:
#Initializing empty lists for storage
api_calls = []
mon_name = []
gen_list = []
gen_mon = {}

#Calling the Generation API
for i in range(1,10):
    with open(f'../data/raw/pokemon_list_gen_{i}.json', mode='w') as f:
        request = requests.get(f"https://pokeapi.co/api/v2/generation/{i}")
        pokemon_json = request.json()
        json.dump(pokemon_json,f,indent=4)
    with open(f'../data/raw/pokemon_list_gen_{i}.json', mode='r') as f:
        data = json.load(f)
        df = pd.json_normalize(
            data,
            record_path= 'pokemon_species',
            meta = 'name',
            record_prefix= 'pokemon_'
        )

#Storing the API call URL and the Pokemon names for use in later API calls
    for i in range(len(df['pokemon_url'])):
        api_calls.append(df['pokemon_url'][i])
        mon_name.append(df['pokemon_name'][i])

#Creating a generation list for later usage in renaming columns
    gen_list.append(df['name'][0])

#Creating a dictionary of every Pokemon added in each Generation for later usage in assigning Generation to a dataframe
    for name in df['pokemon_name']:
        if df['name'][0] not in gen_mon.keys():
            gen_mon[df['name'][0]] = [name]
        else:
            gen_mon[df['name'][0]].append(name)

Now that I have a list of all the different Pokemon species' APIs, I am going to call each species' API to get the API calls for each Pokemon form individually (ex: all three types of Wormadam cloaks rather than just the Wormadam species as a whole). But, first, I am going to create a function to perform the remaining API calls for me.

### Pokemon Species Data

In [3]:
def call_api(call_list,name_list,file_suffix):
##Takes in a list of APIs to call, a list of names for the files, and a suffix for the file to call and store .json data from an API##
    for i in range(len(call_list)):
        with open(f'../data/raw/{name_list[i]}_{file_suffix}.json', mode='w') as f:
            request = requests.get(call_list[i])
            pokemon_json = request.json()
            json.dump(pokemon_json,f,indent=4)

In [4]:
call_api(api_calls,mon_name,'spec')

In [5]:
#Initializing empty lists for storage
stat_calls = []
form_name = []

#Getting the list of each Pokemon form from API alongside calls
for i in range(len(api_calls)):
        with open(f'../data/raw/{mon_name[i]}_spec.json', mode='r') as f:
                data = json.load(f)
                df = pd.json_normalize(
                data,
                record_path = 'varieties',
                sep = '_'
                )

        for i in range(len(df['pokemon_url'])):
                stat_calls.append(df['pokemon_url'][i])
                form_name.append(df['pokemon_name'][i])

### Pokemon Stats Data

In [6]:
call_api(stat_calls,form_name,'stat')

In [7]:
print(api_calls)

['https://pokeapi.co/api/v2/pokemon-species/1/', 'https://pokeapi.co/api/v2/pokemon-species/4/', 'https://pokeapi.co/api/v2/pokemon-species/7/', 'https://pokeapi.co/api/v2/pokemon-species/10/', 'https://pokeapi.co/api/v2/pokemon-species/13/', 'https://pokeapi.co/api/v2/pokemon-species/16/', 'https://pokeapi.co/api/v2/pokemon-species/19/', 'https://pokeapi.co/api/v2/pokemon-species/21/', 'https://pokeapi.co/api/v2/pokemon-species/23/', 'https://pokeapi.co/api/v2/pokemon-species/27/', 'https://pokeapi.co/api/v2/pokemon-species/29/', 'https://pokeapi.co/api/v2/pokemon-species/32/', 'https://pokeapi.co/api/v2/pokemon-species/37/', 'https://pokeapi.co/api/v2/pokemon-species/41/', 'https://pokeapi.co/api/v2/pokemon-species/43/', 'https://pokeapi.co/api/v2/pokemon-species/46/', 'https://pokeapi.co/api/v2/pokemon-species/48/', 'https://pokeapi.co/api/v2/pokemon-species/50/', 'https://pokeapi.co/api/v2/pokemon-species/52/', 'https://pokeapi.co/api/v2/pokemon-species/54/', 'https://pokeapi.co/api/v2/pokemon-species/56/', 'https://pokeapi.co/api/v2/pokemon-species/58/', 'https://pokeapi.co/api/v2/pokemon-species/60/', 'https://pokeapi.co/api/v2/pokemon-species/63/', 'https://pokeapi.co/api/v2/pokemon-species/66/', 'https://pokeapi.co/api/v2/pokemon-species/69/', 'https://pokeapi.co/api/v2/pokemon-species/72/', 'https://pokeapi.co/api/v2/pokemon-species/74/', 'https://pokeapi.co/api/v2/pokemon-species/3/', 'https://pokeapi.co/api/v2/pokemon-species/5/', 'https://pokeapi.co/api/v2/pokemon-species/6/', 'https://pokeapi.co/api/v2/pokemon-species/8/', 'https://pokeapi.co/api/v2/pokemon-species/9/', 'https://pokeapi.co/api/v2/pokemon-species/11/', 'https://pokeapi.co/api/v2/pokemon-species/12/', 'https://pokeapi.co/api/v2/pokemon-species/14/', 'https://pokeapi.co/api/v2/pokemon-species/15/', 'https://pokeapi.co/api/v2/pokemon-species/17/', 'https://pokeapi.co/api/v2/pokemon-species/18/', 'https://pokeapi.co/api/v2/pokemon-species/20/', 'https://pokeapi.co/api/v2/pokemon-species/22/', 'https://pokeapi.co/api/v2/pokemon-species/24/', 'https://pokeapi.co/api/v2/pokemon-species/25/', 'https://pokeapi.co/api/v2/pokemon-species/26/', 'https://pokeapi.co/api/v2/pokemon-species/28/', 'https://pokeapi.co/api/v2/pokemon-species/30/', 'https://pokeapi.co/api/v2/pokemon-species/31/', 'https://pokeapi.co/api/v2/pokemon-species/33/', 'https://pokeapi.co/api/v2/pokemon-species/34/', 'https://pokeapi.co/api/v2/pokemon-species/35/', 'https://pokeapi.co/api/v2/pokemon-species/36/', 'https://pokeapi.co/api/v2/pokemon-species/38/', 'https://pokeapi.co/api/v2/pokemon-species/39/', 'https://pokeapi.co/api/v2/pokemon-species/40/', 'https://pokeapi.co/api/v2/pokemon-species/42/', 'https://pokeapi.co/api/v2/pokemon-species/44/', 'https://pokeapi.co/api/v2/pokemon-species/45/', 'https://pokeapi.co/api/v2/pokemon-species/47/', 'https://pokeapi.co/api/v2/pokemon-species/49/', 'https://pokeapi.co/api/v2/pokemon-species/51/', 'https://pokeapi.co/api/v2/pokemon-species/53/', 'https://pokeapi.co/api/v2/pokemon-species/55/', 'https://pokeapi.co/api/v2/pokemon-species/57/', 'https://pokeapi.co/api/v2/pokemon-species/59/', 'https://pokeapi.co/api/v2/pokemon-species/61/', 'https://pokeapi.co/api/v2/pokemon-species/62/', 'https://pokeapi.co/api/v2/pokemon-species/64/', 'https://pokeapi.co/api/v2/pokemon-species/65/', 'https://pokeapi.co/api/v2/pokemon-species/67/', 'https://pokeapi.co/api/v2/pokemon-species/68/', 'https://pokeapi.co/api/v2/pokemon-species/70/', 'https://pokeapi.co/api/v2/pokemon-species/71/', 'https://pokeapi.co/api/v2/pokemon-species/73/', 'https://pokeapi.co/api/v2/pokemon-species/75/', 'https://pokeapi.co/api/v2/pokemon-species/77/', 'https://pokeapi.co/api/v2/pokemon-species/79/', 'https://pokeapi.co/api/v2/pokemon-species/81/', 'https://pokeapi.co/api/v2/pokemon-species/83/', 'https://pokeapi.co/api/v2/pokemon-species/84/', 'https://pokeapi.co/api/v2/pokemon-species/86/', 'https://pokeapi.co/api/v2/pokemon-species/88/', 'https://pokeapi.co/api/v2/pokemon-species/90/', 'https://pokeapi.co/api/v2/pokemon-species/92/', 'https://pokeapi.co/api/v2/pokemon-species/95/', 'https://pokeapi.co/api/v2/pokemon-species/96/', 'https://pokeapi.co/api/v2/pokemon-species/98/', 'https://pokeapi.co/api/v2/pokemon-species/100/', 'https://pokeapi.co/api/v2/pokemon-species/102/', 'https://pokeapi.co/api/v2/pokemon-species/104/', 'https://pokeapi.co/api/v2/pokemon-species/108/', 'https://pokeapi.co/api/v2/pokemon-species/109/', 'https://pokeapi.co/api/v2/pokemon-species/111/', 'https://pokeapi.co/api/v2/pokemon-species/114/', 'https://pokeapi.co/api/v2/pokemon-species/115/', 'https://pokeapi.co/api/v2/pokemon-species/116/', 'https://pokeapi.co/api/v2/pokemon-species/118/', 'https://pokeapi.co/api/v2/pokemon-species/120/', 'https://pokeapi.co/api/v2/pokemon-species/123/', 'https://pokeapi.co/api/v2/pokemon-species/127/', 'https://pokeapi.co/api/v2/pokemon-species/128/', 'https://pokeapi.co/api/v2/pokemon-species/129/', 'https://pokeapi.co/api/v2/pokemon-species/131/', 'https://pokeapi.co/api/v2/pokemon-species/132/', 'https://pokeapi.co/api/v2/pokemon-species/133/', 'https://pokeapi.co/api/v2/pokemon-species/137/', 'https://pokeapi.co/api/v2/pokemon-species/138/', 'https://pokeapi.co/api/v2/pokemon-species/140/', 'https://pokeapi.co/api/v2/pokemon-species/142/', 'https://pokeapi.co/api/v2/pokemon-species/144/', 'https://pokeapi.co/api/v2/pokemon-species/145/', 'https://pokeapi.co/api/v2/pokemon-species/146/', 'https://pokeapi.co/api/v2/pokemon-species/147/', 'https://pokeapi.co/api/v2/pokemon-species/150/', 'https://pokeapi.co/api/v2/pokemon-species/78/', 'https://pokeapi.co/api/v2/pokemon-species/80/', 'https://pokeapi.co/api/v2/pokemon-species/82/', 'https://pokeapi.co/api/v2/pokemon-species/85/', 'https://pokeapi.co/api/v2/pokemon-species/87/', 'https://pokeapi.co/api/v2/pokemon-species/89/', 'https://pokeapi.co/api/v2/pokemon-species/91/', 'https://pokeapi.co/api/v2/pokemon-species/93/', 'https://pokeapi.co/api/v2/pokemon-species/94/', 'https://pokeapi.co/api/v2/pokemon-species/97/', 'https://pokeapi.co/api/v2/pokemon-species/99/', 'https://pokeapi.co/api/v2/pokemon-species/101/', 'https://pokeapi.co/api/v2/pokemon-species/103/', 'https://pokeapi.co/api/v2/pokemon-species/105/', 'https://pokeapi.co/api/v2/pokemon-species/106/', 'https://pokeapi.co/api/v2/pokemon-species/107/', 'https://pokeapi.co/api/v2/pokemon-species/110/', 'https://pokeapi.co/api/v2/pokemon-species/112/', 'https://pokeapi.co/api/v2/pokemon-species/113/', 'https://pokeapi.co/api/v2/pokemon-species/117/', 'https://pokeapi.co/api/v2/pokemon-species/119/', 'https://pokeapi.co/api/v2/pokemon-species/121/', 'https://pokeapi.co/api/v2/pokemon-species/122/', 'https://pokeapi.co/api/v2/pokemon-species/124/', 'https://pokeapi.co/api/v2/pokemon-species/125/', 'https://pokeapi.co/api/v2/pokemon-species/126/', 'https://pokeapi.co/api/v2/pokemon-species/130/', 'https://pokeapi.co/api/v2/pokemon-species/134/', 'https://pokeapi.co/api/v2/pokemon-species/135/', 'https://pokeapi.co/api/v2/pokemon-species/136/', 'https://pokeapi.co/api/v2/pokemon-species/139/', 'https://pokeapi.co/api/v2/pokemon-species/141/', 'https://pokeapi.co/api/v2/pokemon-species/143/', 'https://pokeapi.co/api/v2/pokemon-species/148/', 'https://pokeapi.co/api/v2/pokemon-species/149/', 'https://pokeapi.co/api/v2/pokemon-species/151/', 'https://pokeapi.co/api/v2/pokemon-species/2/', 'https://pokeapi.co/api/v2/pokemon-species/76/', 'https://pokeapi.co/api/v2/pokemon-species/185/', 'https://pokeapi.co/api/v2/pokemon-species/152/', 'https://pokeapi.co/api/v2/pokemon-species/178/', 'https://pokeapi.co/api/v2/pokemon-species/180/', 'https://pokeapi.co/api/v2/pokemon-species/155/', 'https://pokeapi.co/api/v2/pokemon-species/181/', 'https://pokeapi.co/api/v2/pokemon-species/182/', 'https://pokeapi.co/api/v2/pokemon-species/158/', 'https://pokeapi.co/api/v2/pokemon-species/183/', 'https://pokeapi.co/api/v2/pokemon-species/184/', 'https://pokeapi.co/api/v2/pokemon-species/161/', 'https://pokeapi.co/api/v2/pokemon-species/196/', 'https://pokeapi.co/api/v2/pokemon-species/163/', 'https://pokeapi.co/api/v2/pokemon-species/197/', 'https://pokeapi.co/api/v2/pokemon-species/165/', 'https://pokeapi.co/api/v2/pokemon-species/199/', 'https://pokeapi.co/api/v2/pokemon-species/167/', 'https://pokeapi.co/api/v2/pokemon-species/202/', 'https://pokeapi.co/api/v2/pokemon-species/205/', 'https://pokeapi.co/api/v2/pokemon-species/170/', 'https://pokeapi.co/api/v2/pokemon-species/208/', 'https://pokeapi.co/api/v2/pokemon-species/172/', 'https://pokeapi.co/api/v2/pokemon-species/173/', 'https://pokeapi.co/api/v2/pokemon-species/174/', 'https://pokeapi.co/api/v2/pokemon-species/175/', 'https://pokeapi.co/api/v2/pokemon-species/177/', 'https://pokeapi.co/api/v2/pokemon-species/179/', 'https://pokeapi.co/api/v2/pokemon-species/187/', 'https://pokeapi.co/api/v2/pokemon-species/190/', 'https://pokeapi.co/api/v2/pokemon-species/191/', 'https://pokeapi.co/api/v2/pokemon-species/193/', 'https://pokeapi.co/api/v2/pokemon-species/194/', 'https://pokeapi.co/api/v2/pokemon-species/198/', 'https://pokeapi.co/api/v2/pokemon-species/200/', 'https://pokeapi.co/api/v2/pokemon-species/201/', 'https://pokeapi.co/api/v2/pokemon-species/203/', 'https://pokeapi.co/api/v2/pokemon-species/204/', 'https://pokeapi.co/api/v2/pokemon-species/206/', 'https://pokeapi.co/api/v2/pokemon-species/207/', 'https://pokeapi.co/api/v2/pokemon-species/209/', 'https://pokeapi.co/api/v2/pokemon-species/211/', 'https://pokeapi.co/api/v2/pokemon-species/213/', 'https://pokeapi.co/api/v2/pokemon-species/214/', 'https://pokeapi.co/api/v2/pokemon-species/215/', 'https://pokeapi.co/api/v2/pokemon-species/216/', 'https://pokeapi.co/api/v2/pokemon-species/218/', 'https://pokeapi.co/api/v2/pokemon-species/220/', 'https://pokeapi.co/api/v2/pokemon-species/222/', 'https://pokeapi.co/api/v2/pokemon-species/223/', 'https://pokeapi.co/api/v2/pokemon-species/225/', 'https://pokeapi.co/api/v2/pokemon-species/154/', 'https://pokeapi.co/api/v2/pokemon-species/156/', 'https://pokeapi.co/api/v2/pokemon-species/157/', 'https://pokeapi.co/api/v2/pokemon-species/159/', 'https://pokeapi.co/api/v2/pokemon-species/160/', 'https://pokeapi.co/api/v2/pokemon-species/162/', 'https://pokeapi.co/api/v2/pokemon-species/164/', 'https://pokeapi.co/api/v2/pokemon-species/166/', 'https://pokeapi.co/api/v2/pokemon-species/168/', 'https://pokeapi.co/api/v2/pokemon-species/171/', 'https://pokeapi.co/api/v2/pokemon-species/176/', 'https://pokeapi.co/api/v2/pokemon-species/210/', 'https://pokeapi.co/api/v2/pokemon-species/212/', 'https://pokeapi.co/api/v2/pokemon-species/217/', 'https://pokeapi.co/api/v2/pokemon-species/219/', 'https://pokeapi.co/api/v2/pokemon-species/221/', 'https://pokeapi.co/api/v2/pokemon-species/224/', 'https://pokeapi.co/api/v2/pokemon-species/227/', 'https://pokeapi.co/api/v2/pokemon-species/228/', 'https://pokeapi.co/api/v2/pokemon-species/231/', 'https://pokeapi.co/api/v2/pokemon-species/234/', 'https://pokeapi.co/api/v2/pokemon-species/235/', 'https://pokeapi.co/api/v2/pokemon-species/236/', 'https://pokeapi.co/api/v2/pokemon-species/238/', 'https://pokeapi.co/api/v2/pokemon-species/239/', 'https://pokeapi.co/api/v2/pokemon-species/240/', 'https://pokeapi.co/api/v2/pokemon-species/241/', 'https://pokeapi.co/api/v2/pokemon-species/243/', 'https://pokeapi.co/api/v2/pokemon-species/244/', 'https://pokeapi.co/api/v2/pokemon-species/245/', 'https://pokeapi.co/api/v2/pokemon-species/246/', 'https://pokeapi.co/api/v2/pokemon-species/249/', 'https://pokeapi.co/api/v2/pokemon-species/250/', 'https://pokeapi.co/api/v2/pokemon-species/251/', 'https://pokeapi.co/api/v2/pokemon-species/229/', 'https://pokeapi.co/api/v2/pokemon-species/230/', 'https://pokeapi.co/api/v2/pokemon-species/232/', 'https://pokeapi.co/api/v2/pokemon-species/233/', 'https://pokeapi.co/api/v2/pokemon-species/237/', 'https://pokeapi.co/api/v2/pokemon-species/153/', 'https://pokeapi.co/api/v2/pokemon-species/169/', 'https://pokeapi.co/api/v2/pokemon-species/186/', 'https://pokeapi.co/api/v2/pokemon-species/188/', 'https://pokeapi.co/api/v2/pokemon-species/189/', 'https://pokeapi.co/api/v2/pokemon-species/192/', 'https://pokeapi.co/api/v2/pokemon-species/195/', 'https://pokeapi.co/api/v2/pokemon-species/226/', 'https://pokeapi.co/api/v2/pokemon-species/242/', 'https://pokeapi.co/api/v2/pokemon-species/247/', 'https://pokeapi.co/api/v2/pokemon-species/248/', 'https://pokeapi.co/api/v2/pokemon-species/350/', 'https://pokeapi.co/api/v2/pokemon-species/354/', 'https://pokeapi.co/api/v2/pokemon-species/252/', 'https://pokeapi.co/api/v2/pokemon-species/255/', 'https://pokeapi.co/api/v2/pokemon-species/258/', 'https://pokeapi.co/api/v2/pokemon-species/261/', 'https://pokeapi.co/api/v2/pokemon-species/263/', 'https://pokeapi.co/api/v2/pokemon-species/265/', 'https://pokeapi.co/api/v2/pokemon-species/270/', 'https://pokeapi.co/api/v2/pokemon-species/273/', 'https://pokeapi.co/api/v2/pokemon-species/276/', 'https://pokeapi.co/api/v2/pokemon-species/278/', 'https://pokeapi.co/api/v2/pokemon-species/280/', 'https://pokeapi.co/api/v2/pokemon-species/283/', 'https://pokeapi.co/api/v2/pokemon-species/285/', 'https://pokeapi.co/api/v2/pokemon-species/287/', 'https://pokeapi.co/api/v2/pokemon-species/290/', 'https://pokeapi.co/api/v2/pokemon-species/293/', 'https://pokeapi.co/api/v2/pokemon-species/296/', 'https://pokeapi.co/api/v2/pokemon-species/298/', 'https://pokeapi.co/api/v2/pokemon-species/299/', 'https://pokeapi.co/api/v2/pokemon-species/300/', 'https://pokeapi.co/api/v2/pokemon-species/279/', 'https://pokeapi.co/api/v2/pokemon-species/281/', 'https://pokeapi.co/api/v2/pokemon-species/282/', 'https://pokeapi.co/api/v2/pokemon-species/284/', 'https://pokeapi.co/api/v2/pokemon-species/286/', 'https://pokeapi.co/api/v2/pokemon-species/288/', 'https://pokeapi.co/api/v2/pokemon-species/289/', 'https://pokeapi.co/api/v2/pokemon-species/291/', 'https://pokeapi.co/api/v2/pokemon-species/292/', 'https://pokeapi.co/api/v2/pokemon-species/294/', 'https://pokeapi.co/api/v2/pokemon-species/295/', 'https://pokeapi.co/api/v2/pokemon-species/297/', 'https://pokeapi.co/api/v2/pokemon-species/302/', 'https://pokeapi.co/api/v2/pokemon-species/303/', 'https://pokeapi.co/api/v2/pokemon-species/304/', 'https://pokeapi.co/api/v2/pokemon-species/307/', 'https://pokeapi.co/api/v2/pokemon-species/309/', 'https://pokeapi.co/api/v2/pokemon-species/311/', 'https://pokeapi.co/api/v2/pokemon-species/312/', 'https://pokeapi.co/api/v2/pokemon-species/313/', 'https://pokeapi.co/api/v2/pokemon-species/314/', 'https://pokeapi.co/api/v2/pokemon-species/316/', 'https://pokeapi.co/api/v2/pokemon-species/318/', 'https://pokeapi.co/api/v2/pokemon-species/320/', 'https://pokeapi.co/api/v2/pokemon-species/322/', 'https://pokeapi.co/api/v2/pokemon-species/324/', 'https://pokeapi.co/api/v2/pokemon-species/325/', 'https://pokeapi.co/api/v2/pokemon-species/327/', 'https://pokeapi.co/api/v2/pokemon-species/328/', 'https://pokeapi.co/api/v2/pokemon-species/331/', 'https://pokeapi.co/api/v2/pokemon-species/333/', 'https://pokeapi.co/api/v2/pokemon-species/335/', 'https://pokeapi.co/api/v2/pokemon-species/336/', 'https://pokeapi.co/api/v2/pokemon-species/337/', 'https://pokeapi.co/api/v2/pokemon-species/338/', 'https://pokeapi.co/api/v2/pokemon-species/339/', 'https://pokeapi.co/api/v2/pokemon-species/341/', 'https://pokeapi.co/api/v2/pokemon-species/343/', 'https://pokeapi.co/api/v2/pokemon-species/345/', 'https://pokeapi.co/api/v2/pokemon-species/347/', 'https://pokeapi.co/api/v2/pokemon-species/349/', 'https://pokeapi.co/api/v2/pokemon-species/351/', 'https://pokeapi.co/api/v2/pokemon-species/352/', 'https://pokeapi.co/api/v2/pokemon-species/353/', 'https://pokeapi.co/api/v2/pokemon-species/355/', 'https://pokeapi.co/api/v2/pokemon-species/357/', 'https://pokeapi.co/api/v2/pokemon-species/359/', 'https://pokeapi.co/api/v2/pokemon-species/360/', 'https://pokeapi.co/api/v2/pokemon-species/361/', 'https://pokeapi.co/api/v2/pokemon-species/363/', 'https://pokeapi.co/api/v2/pokemon-species/366/', 'https://pokeapi.co/api/v2/pokemon-species/369/', 'https://pokeapi.co/api/v2/pokemon-species/370/', 'https://pokeapi.co/api/v2/pokemon-species/371/', 'https://pokeapi.co/api/v2/pokemon-species/374/', 'https://pokeapi.co/api/v2/pokemon-species/305/', 'https://pokeapi.co/api/v2/pokemon-species/362/', 'https://pokeapi.co/api/v2/pokemon-species/364/', 'https://pokeapi.co/api/v2/pokemon-species/365/', 'https://pokeapi.co/api/v2/pokemon-species/367/', 'https://pokeapi.co/api/v2/pokemon-species/368/', 'https://pokeapi.co/api/v2/pokemon-species/372/', 'https://pokeapi.co/api/v2/pokemon-species/373/', 'https://pokeapi.co/api/v2/pokemon-species/375/', 'https://pokeapi.co/api/v2/pokemon-species/377/', 'https://pokeapi.co/api/v2/pokemon-species/378/', 'https://pokeapi.co/api/v2/pokemon-species/379/', 'https://pokeapi.co/api/v2/pokemon-species/380/', 'https://pokeapi.co/api/v2/pokemon-species/381/', 'https://pokeapi.co/api/v2/pokemon-species/382/', 'https://pokeapi.co/api/v2/pokemon-species/383/', 'https://pokeapi.co/api/v2/pokemon-species/384/', 'https://pokeapi.co/api/v2/pokemon-species/385/', 'https://pokeapi.co/api/v2/pokemon-species/386/', 'https://pokeapi.co/api/v2/pokemon-species/253/', 'https://pokeapi.co/api/v2/pokemon-species/254/', 'https://pokeapi.co/api/v2/pokemon-species/256/', 'https://pokeapi.co/api/v2/pokemon-species/257/', 'https://pokeapi.co/api/v2/pokemon-species/259/', 'https://pokeapi.co/api/v2/pokemon-species/260/', 'https://pokeapi.co/api/v2/pokemon-species/262/', 'https://pokeapi.co/api/v2/pokemon-species/264/', 'https://pokeapi.co/api/v2/pokemon-species/266/', 'https://pokeapi.co/api/v2/pokemon-species/267/', 'https://pokeapi.co/api/v2/pokemon-species/268/', 'https://pokeapi.co/api/v2/pokemon-species/269/', 'https://pokeapi.co/api/v2/pokemon-species/271/', 'https://pokeapi.co/api/v2/pokemon-species/272/', 'https://pokeapi.co/api/v2/pokemon-species/274/', 'https://pokeapi.co/api/v2/pokemon-species/275/', 'https://pokeapi.co/api/v2/pokemon-species/277/', 'https://pokeapi.co/api/v2/pokemon-species/301/', 'https://pokeapi.co/api/v2/pokemon-species/306/', 'https://pokeapi.co/api/v2/pokemon-species/308/', 'https://pokeapi.co/api/v2/pokemon-species/310/', 'https://pokeapi.co/api/v2/pokemon-species/315/', 'https://pokeapi.co/api/v2/pokemon-species/317/', 'https://pokeapi.co/api/v2/pokemon-species/319/', 'https://pokeapi.co/api/v2/pokemon-species/321/', 'https://pokeapi.co/api/v2/pokemon-species/323/', 'https://pokeapi.co/api/v2/pokemon-species/326/', 'https://pokeapi.co/api/v2/pokemon-species/329/', 'https://pokeapi.co/api/v2/pokemon-species/330/', 'https://pokeapi.co/api/v2/pokemon-species/332/', 'https://pokeapi.co/api/v2/pokemon-species/334/', 'https://pokeapi.co/api/v2/pokemon-species/340/', 'https://pokeapi.co/api/v2/pokemon-species/342/', 'https://pokeapi.co/api/v2/pokemon-species/344/', 'https://pokeapi.co/api/v2/pokemon-species/346/', 'https://pokeapi.co/api/v2/pokemon-species/348/', 'https://pokeapi.co/api/v2/pokemon-species/356/', 'https://pokeapi.co/api/v2/pokemon-species/358/', 'https://pokeapi.co/api/v2/pokemon-species/376/', 'https://pokeapi.co/api/v2/pokemon-species/387/', 'https://pokeapi.co/api/v2/pokemon-species/390/', 'https://pokeapi.co/api/v2/pokemon-species/393/', 'https://pokeapi.co/api/v2/pokemon-species/396/', 'https://pokeapi.co/api/v2/pokemon-species/399/', 'https://pokeapi.co/api/v2/pokemon-species/401/', 'https://pokeapi.co/api/v2/pokemon-species/403/', 'https://pokeapi.co/api/v2/pokemon-species/406/', 'https://pokeapi.co/api/v2/pokemon-species/408/', 'https://pokeapi.co/api/v2/pokemon-species/410/', 'https://pokeapi.co/api/v2/pokemon-species/412/', 'https://pokeapi.co/api/v2/pokemon-species/415/', 'https://pokeapi.co/api/v2/pokemon-species/417/', 'https://pokeapi.co/api/v2/pokemon-species/418/', 'https://pokeapi.co/api/v2/pokemon-species/420/', 'https://pokeapi.co/api/v2/pokemon-species/422/', 'https:

All of the necessary calls have been made, and all the data stored in the 'raw' folder under 'data'.

## Storing the collected data in dataframes

Now that the data has been collected and safely stored, it is time to arrange the data into neat dataframes.

### How many dataframes will be created?
There are going to be two different dataframes: one containing the species data of the Pokemon, and one containing the actual stats data of the Pokemon.

### What will each dataframe contain?
For the dataframe with the species data, each row is going to contain the ID of the Pokemon, the name of the Pokemon, the flags of whether the Pokemon is a baby, a legendary, or a mythical, and the Generation that the Pokemon is associated with.

For the dataframe with the stats data, each row is going to contain the ID, name of the Pokemon, and its associated Generation once again, and all of their individual base stats and the names of those stats.

### Why two different dataframes?

There are a couple of reasons why two different dataframes are needed:
- Having the species and the individual stats data separated out will make for easier analysis later, as I can choose to combine the dataframes with pd.merge() if the need arises, or I can keep them separate and perform individual analyses on the data they contain
- The dataframe containing the stats data has six rows for each Pokemon (one for each kind of base stat), while the dataframe containing the species data has one row for each Pokemon, so attempting to combine them out of the gate will lead to misaligned dataframes and bad data
- The data is stored in two different API calls, so creating two different dataframes is easier for me, personally

### Why am I creating and storing the dataframes here? Why not in NB02?

I have already stored all of the API calls for both species and stats data in this notebook, and variables do not carry over between notebooks. As such, to avoid repeating code as much as possible, I am going to create the dataframes here.

In [ ]:
#Creating the dataframe with species data
spec_df = ''
with open(f'../data/raw/{mon_name[0]}_spec.json', mode='r') as f:
        data = json.load(f)
        df = pd.json_normalize(
            data,
            record_path = 'varieties',
            meta = ['id', 'name', 'is_baby', 'is_legendary', 'is_mythical'],
            sep='_'
        )
        gen_df = pd.DataFrame(data['generation'],index=[0]).rename(columns={'name':'gen', 'url':'gen_url'})

initial_df = pd.concat([df,gen_df],axis=1)


for i in range(1, len(api_calls)):
        with open(f'../data/raw/{mon_name[i]}_spec.json', mode='r') as f:
                data = json.load(f)
                df = pd.json_normalize(
                        data,
                        record_path = 'varieties',
                        meta = ['id', 'name', 'is_baby', 'is_legendary', 'is_mythical'],
                        sep='_'
                )
                gen_df = pd.DataFrame(data['generation'],index=[0]).rename(columns={'name':'gen', 'url':'gen_url'})
        dfc = pd.concat([df,gen_df],axis=1)
        spec_df = pd.concat([initial_df,dfc],axis=0, ignore_index = True)
        initial_df = spec_df

,is_default,pokemon_name,pokemon_url,id,name,is_baby,is_legendary,is_mythical,gen,gen_url
0,True,bulbasaur,https://pokeapi.co/api/v2/pokemon/1/,1,bulbasaur,False,False,False,generation-i,https://pokeapi.co/api/v2/generation/1/
1,True,charmander,https://pokeapi.co/api/v2/pokemon/4/,4,charmander,False,False,False,generation-i,https://pokeapi.co/api/v2/generation/1/
2,True,squirtle,https://pokeapi.co/api/v2/pokemon/7/,7,squirtle,False,False,False,generation-i,https://pokeapi.co/api/v2/generation/1/
3,True,caterpie,https://pokeapi.co/api/v2/pokemon/10/,10,caterpie,False,False,False,generation-i,https://pokeapi.co/api/v2/generation/1/
4,True,weedle,https://pokeapi.co/api/v2/pokemon/13/,13,weedle,False,False,False,generation-i,https://pokeapi.co/api/v2/generation/1/
...,...,...,...,...,...,...,...,...,...,...
1346,True,arboliva,https://pokeapi.co/api/v2/pokemon/930/,930,arboliva,False,False,False,generation-ix,https://pokeapi.co/api/v2/generation/9/
1347,True,revavroom,https://pokeapi.co/api/v2/pokemon/966/,966,revavroom,False,False,False,generation-ix,https://pokeapi.co/api/v2/generation/9/
1348,True,arctibax,https://pokeapi.co/api/v2/pokemon/997/,997,arctibax,False,False,False,generation-ix,https://pokeapi.co/api/v2/generation/9/
1349,True,baxcalibur,https://pokeapi.co/api/v2/pokemon/998/,998,baxcalibur,False,False,False,generation-ix,https://pokeapi.co/api/v2/generation/9/
1350,False,baxcalibur-mega,https://pokeapi.co/api/v2/pokemon/10325/,998,baxcalibur,False,False,False,NaN,NaN

The use of .rename(): When I was creating the dataframe, I found that I had to add Generation separately due to the way it was stored in the API and then concatenate it onto the dataframe by row, but when I tried to concatenate them originally, I ran into name errors since the name of the Generation and the URL to call the generation were under the same name as the column storing the Pokemon name and the URL to get data about the Pokemon themselves. As such, I used .rename() to change the conflicting names of columns to something else, passing a dictionary with the original column names as keys and my new column names as values.

In [ ]:
## Creating the dataframe with stats data
with open(f'../data/raw/{form_name[0]}_stat.json', mode='r') as f:
    data = json.load(f)
    initial_df = pd.json_normalize(
        data,
        record_path = 'stats',
        meta = ['id', 'name'],
        sep='_'
    )

for i in range(1, len(stat_calls)):
    with open(f'../data/raw/{form_name[i]}_stat.json', mode='r') as f:
            data = json.load(f)
            df = pd.json_normalize(
                data,
                record_path = 'stats',
                meta = ['id','name'],
                sep='_'
            )
    stats_df = pd.concat([initial_df,df],axis=0, ignore_index = True)
    initial_df = stats_df

,base_stat,effort,stat_name,stat_url,id,name
0,45,0,hp,https://pokeapi.co/api/v2/stat/1/,1,bulbasaur
1,49,0,attack,https://pokeapi.co/api/v2/stat/2/,1,bulbasaur
2,49,0,defense,https://pokeapi.co/api/v2/stat/3/,1,bulbasaur
3,65,1,special-attack,https://pokeapi.co/api/v2/stat/4/,1,bulbasaur
4,65,0,special-defense,https://pokeapi.co/api/v2/stat/5/,1,bulbasaur
...,...,...,...,...,...,...
8101,175,0,attack,https://pokeapi.co/api/v2/stat/2/,10325,baxcalibur-mega
8102,117,0,defense,https://pokeapi.co/api/v2/stat/3/,10325,baxcalibur-mega
8103,105,0,special-attack,https://pokeapi.co/api/v2/stat/4/,10325,baxcalibur-mega
8104,101,0,special-defense,https://pokeapi.co/api/v2/stat/5/,10325,baxcalibur-mega
8105,87,0,speed,https://pokeapi.co/api/v2/stat/6/,10325,baxcalibur-mega

Now that the two dataframes have been created, it is time to save them as csv files for usage in later notebooks.

In [20]:
spec_df.to_csv('../data/processed/spec_df.csv')

stats_df.to_csv('../data/processed/stats_df.csv')